language: node_js
sudo: false
node_js:
  - '10'
before_script:
  - ./node_modules/.bin/eslint --quiet .
  - docker-compose pull mongo
  - docker-compose up -d mongo
  - sleep 10
  - mongo --eval 'rs.initiate()'
  - sleep 15
install:
  - npm install
after_success:
  - npm run coveralls
